---
# email of administrators for reports
#  - asd@mail.ru
#  - vvv@yandex.ru
admin_emails: []

# required
# smtp_server: "smtp.gmail.com"
smtp_server: ""
smtp_port: 465
smtp_tls: true

# required
#smtp_login: "asd@gmail.com"
smtp_login: ""

# required
#smtp_password: "..."
smtp_password: ""

# required. Sender email.
smtp_from: ""

# 0 - every day
# 1-7 monday-sunday
ok_report_day: 1

# Filepath to cache file
state_file: state.yaml

# If domain expire less then expire_soon_days - send report
expire_soon_days: 7

# If domain expire after no_cache_days_before_expire - skip request domain info
no_cache_days_before_expire: 60

# Log format: Hierarchy, Lines
# Hierarchy - better for read full log by human
# Lines - repeat all context variables on every line. Better for grep.
log_format: Hierarchy

# Debug, Info, Error
log_level: Debug

# Filepath to customers description
customers_file: customers.yaml
